# Generated by Django 5.2 on 2025-04-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredmovie',
            name='is_featured',
            field=models.BooleanField(default=True, help_text='Show in featured section on homepage', verbose_name='Featured'),
        ),
    ]
