# Generated by Django 5.2 on 2025-04-07 08:06

import django.core.validators
import django.db.models.deletion
import media_gallery.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Media Category',
                'verbose_name_plural': 'Media Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('event', 'Event')], max_length=50, verbose_name='Media Type')),
                ('file', models.FileField(blank=True, null=True, upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'webm'])], verbose_name='Media File')),
                ('media_url', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='Media URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', validators=[media_gallery.validators.validate_image_quality], verbose_name='Thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='media_gallery.mediacategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Media Item',
                'verbose_name_plural': 'Media Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
